### ISSUE TITLE
Header Names are Case-Insensitive

### ISSUE THREAD

**Issue by zimdo** [firebase/TubeSock#12]
From RFC 2616 - "Hypertext Transfer Protocol -- HTTP/1.1", Section 4.2, "Message Headers":

Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive.

The updating RFC 7230 does not list any changes from RFC 2616 at this part.

**Comment by zimdo** [comment]
![screen shot 2015-08-18 at 12 43 02 pm](https://cloud.githubusercontent.com/assets/185401/9336282/b3e2aa28-45a6-11e5-9794-2623bf0fa700.png)

**Comment by mwaclawek** [comment]
Didn't see this issue before. Pull request is here: https://github.com/firebase/TubeSock/pull/13

**Comment by rockwotj** [comment]
The PR was merged.
