### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException length=112; regionStart=0; regionLength=-1

### ISSUE THREAD

**Issue by coyarzun89** [firebase/TubeSock#9]
Hi,
I had received several crashes related to this line com.firebase.tubesock.WebSocketReceiver.read(WebSocketReceiver.java:138):

java.lang.ArrayIndexOutOfBoundsException: length=112; regionStart=0; regionLength=-1
       at java.util.Arrays.checkOffsetAndCount(Arrays.java:1731)
       at libcore.io.IoBridge.write(IoBridge.java:451)
       at java.io.FileOutputStream.write(FileOutputStream.java:187)
       at libcore.util.NetTraffic.write(NetTraffic.java:31)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:697)
       at libcore.io.Streams.readFully(Streams.java:81)
       at java.io.DataInputStream.readFully(DataInputStream.java:120)
       at com.firebase.tubesock.WebSocketReceiver.read(WebSocketReceiver.java:138)
       at com.firebase.tubesock.WebSocketReceiver.run(WebSocketReceiver.java:33)

Is there any way to fix it?

thanks in advance!

**Comment by mikelehen** [comment]
Can you confirm you're using a recent version?  I think there was an array out of bounds error fixed a while back.

**Comment by coyarzun89** [comment]
I'm using this version on my build.gradle file:
compile 'com.firebase:firebase-client-android:2.2.1+'

**Comment by mikelehen** [comment]
Hrm, interesting.  Looking closer at the callstack, it seems really peculiar...  as in, this shouldn't be possible.

Can you provide any more detail about what sorts of devices are hitting this?  Our best guess right now is that this is some buggy version of Android or something.

**Comment by coyarzun89** [comment]
This is all the information I had. Apparently, this issue only has happened with this user, but in several times.
<img width="956" alt="screen shot 2015-07-24 at 16 00 40" src="https://cloud.githubusercontent.com/assets/1242575/8882480/8e3ce33e-321d-11e5-818b-d6a8a6606ebb.png">

**Comment by mikelehen** [comment]
Thanks @coyarzun89.

Unfortunately there's not much we can make of this.  As far as we can tell, the exception shouldn't happen unless there's a bug in the android network internals.  Since the user is running a rooted OS, perhaps he's using some non-standard build.

I'm going to close this as it's not particularly actionable. If you are able to get any more information about the issue, let us know and we can take a look again.  Thanks!

**Comment by IceJOKER** [comment]
I also have this issue:

http://joxi.ru/Dr8njo7Cy5GE26.jpg

In my another app also:

http://joxi.ru/bmoOnBXHQqpPmy.jpg (there is just couple crash logs, but in fact over 30-50 per month)

Until now I thought problem with my app, but crashlytics said me that's Firebase's issue.

Please fix it
